apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: {{ .Values.appName }}
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myconfigmapv1.1
          resources:
            requests:
              memory: "16Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "160m"