apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask
