apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  selector:
    app: mywebapp
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
