apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  selector:
    app: mywebapp
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmapv1.1
data:
  BG_COLOR: "#12181b"
  FONT_COLOR: "#FFFFF"
  CUSTOM_HEADER: "Deployed with second config map."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myconfigmapv1.1
          resources:
            requests:
              memory: "16Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "160m"
